pod 'ZBarSDK',  '~> 1.3.1';
pod 'UIView+FrameAdditions';
pod 'UIImage-Categories';
pod 'FlatUIKit';
pod 'FMDB';
pod 'SoundManager';
pod 'Block-KVO';
pod 'ZXingObjC'
pod 'xmlrpc'
pod 'SVProgressHUD'
pod 'CardIO'
pod 'AFNetworking', '~> 1.3.3'